const { _electron: electron } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const base = path.resolve('.test-data'); fs.mkdirSync(base, { recursive: true });
const directory = fs.mkdtempSync(path.join(base, 'ui-'));
const env = { ...process.env, FOCUS_GUARD_TEST_DATA: directory }; delete env.ELECTRON_RUN_AS_NODE;
let application;
async function launch() {
  application = await electron.launch({ ...(process.env.FOCUS_GUARD_EXECUTABLE ? { executablePath: path.resolve(process.env.FOCUS_GUARD_EXECUTABLE), args: [] } : { args: ['.'] }), cwd: path.resolve('.'), env });
  const page = await application.firstWindow();
  page.setDefaultTimeout(15000);
  await page.locator('#new-task').waitFor();
  return page;
}
async function run() {
  let page = await launch();
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.click('#new-task'); await page.fill('#task-name', '企画書の構成を考える');
  await page.fill('#task-memo', '背景・提案・次の一歩を整理する');
  await page.fill('#task-tags', '仕事, 企画');
  await page.locator('#task-form button.primary').click();
  await page.locator('.task-content strong', { hasText: '企画書の構成を考える' }).waitFor();
  await page.click('[data-action="edit"]'); await page.fill('#task-name', '企画書の構成をまとめる'); await page.locator('#task-form button.primary').click();
  await page.click('#new-task'); await page.fill('#task-name', '参考資料を読み返す'); await page.locator('#task-form button.primary').click();
  await page.locator('#tag-filters button', { hasText: '仕事' }).click();
  assert.equal(await page.locator('.task-row').count(), 1);
  assert.equal(await page.locator('.task-content strong').textContent(), '企画書の構成をまとめる');
  await page.fill('#task-search', '該当なし');
  assert.equal(await page.locator('.task-row').count(), 0);
  await page.fill('#task-search', '');
  await page.locator('#tag-filters button', { hasText: 'すべて' }).click();
  assert.equal(await page.locator('.task-row').count(), 2);
  await page.locator('.task-content').first().click();
  await page.screenshot({ path: path.join(base, 'focus-ready.png') });
  assert.equal(await page.locator('#allowed, #add-app-form, #distraction-dialog').count(), 0);
  await page.click('#start');
  await page.locator('#session-panel').waitFor();
  await page.waitForFunction(() => document.getElementById('timer').textContent !== '00:00:00');
  assert.equal(await page.locator('#monitor-status').count(), 0);
  const windows = await application.evaluate(({ BrowserWindow, screen }) => ({ windows: BrowserWindow.getAllWindows().map(w => ({ bounds: w.getBounds(), focusable: w.isFocusable(), onTop: w.isAlwaysOnTop() })), displays: screen.getAllDisplays().map(d => d.workArea) }));
  assert.equal(windows.windows.length, windows.displays.length + 1);
  const widgets = windows.windows.filter(w => !w.focusable);
  assert.equal(widgets.length, windows.displays.length);
  console.log('Overlay geometry:', JSON.stringify(windows));
  assert.ok(widgets.every(w => w.bounds.width <= 340 && w.bounds.height <= 110 && w.onTop));
  for (const d of windows.displays) assert.ok(widgets.some(w => Math.abs(d.x + d.width - w.bounds.x - w.bounds.width) <= 20 && Math.abs(d.y + d.height - w.bounds.y - w.bounds.height) <= 20));
  const overlay = application.windows().find(w => w.url().endsWith('overlay.html'));
  await overlay.locator('#task').waitFor(); await overlay.screenshot({ path: path.join(base, 'focus-widget.png') });
  await page.click('[data-window="minimize"]');
  await page.waitForTimeout(300);
  await overlay.click('#show-main');
  await page.waitForFunction(() => document.hasFocus());
  assert.ok(await application.evaluate(({ BrowserWindow }) => {
    const w = BrowserWindow.getAllWindows().find(w => w.webContents.getURL().endsWith('index.html'));
    return w.isVisible() && !w.isMinimized() && w.isFocused();
  }));
  await page.click('#pause'); await page.waitForFunction(() => document.getElementById('pause').getAttribute('aria-label') === '作業を再開');
  const paused = await page.locator('#timer').textContent();
  await page.waitForTimeout(1200); assert.equal(await page.locator('#timer').textContent(), paused);
  assert.equal(await application.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().length), 1);
  await page.click('#pause');
  await page.screenshot({ path: path.join(base, 'focus-session.png') });
  const originalSession = await page.evaluate(async () => (await window.focusGuard.call('state')).data.active.id);
  await page.locator('.task-content').nth(1).click();
  await page.click('#start');
  await page.waitForFunction(() => document.getElementById('session-name').textContent === '企画書の構成をまとめる');
  assert.equal(await page.locator('.suspended-row').count(), 1);
  await page.locator('[data-resume]').click();
  await page.waitForFunction(() => document.getElementById('session-name').textContent === '参考資料を読み返す');
  assert.equal(await page.evaluate(async () => (await window.focusGuard.call('state')).data.active.id), originalSession);
  await page.locator('[data-finish]').click();
  await page.click('#suspend');
  assert.equal(await page.locator('#session-panel').isVisible(), false);
  await page.screenshot({ path: path.join(base, 'focus-suspended.png') });
  await application.close(); application = null;
  page = await launch();
  await page.locator('[data-resume]').waitFor();
  await page.locator('[data-resume]').click();
  assert.equal(await page.evaluate(async () => (await window.focusGuard.call('state')).data.active.id), originalSession);
  await page.click('#end');
  assert.equal(await application.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().length), 1);
  await page.locator('[data-action="complete"]').first().click();
  await page.click('[data-page="history"]'); await page.locator('.history-row').first().waitFor();
  await page.screenshot({ path: path.join(base, 'focus-history.png') });
  const exportPath = path.join(directory, 'export.jsonl');
  await application.evaluate(({ dialog }, filePath) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath }); }, exportPath);
  await page.click('#export');
  await page.waitForFunction(() => document.getElementById('toast').textContent === 'JSONLファイルを書き出しました。');
  const events = fs.readFileSync(exportPath, 'utf8').trim().split('\n').map(JSON.parse);
  assert.ok(events.every(e => !['distraction', 'app_added'].includes(e.event_type)));
  assert.ok(events.some(e => e.event_type === 'session_completed'));
  assert.deepEqual(errors, []);
  await application.close(); application = null;
  page = await launch();
  await page.waitForFunction(() => document.querySelectorAll('.task-row').length === 1);
  assert.ok((await page.locator('.row-tags').textContent()).includes('仕事'));
  await page.click('#done-tasks'); await page.locator('.task-row.done').waitFor();
  await page.click('[data-page="history"]'); assert.ok(await page.locator('.history-row').count() >= events.length);
  await application.close(); application = null;
  console.log('PASS: tags/search/filter/persistence, task edit/completion, custom minimize control, clickable widget restores main window, pause/resume/end, JSONL export; no renderer errors.');
  console.log(`Screenshots: ${base}`);
}
run().catch(async error => { console.error(error); if (application) { const page = application.windows()[0]; console.error(await page.locator('body').innerText()); await page.screenshot({ path: path.join(base, 'failure.png') }); } process.exitCode = 1; }).finally(async () => { if (application) await application.close(); });
